services:
 noVNC:
  build:
    context: .
    dockerfile_inline: |
      FROM alpine
      RUN apk add novnc
      ENV SERVER=localhost:5900
      CMD ["novnc","--vnc=$SERVER"]
    container_name: novnc-container
    environment:
      - SERVER=truenas.lan:5900
      - TZ=Europe/Berlin
    restart: unless-stopped
