services:
  novnc:
    build: https://github.com/Momi-V/Notizen.git#main:/novnc
    container_name: novnc-01
    environment:
      - SERVER=localhost:5900
      - TZ=ETC/UTC
    restart: unless-stopped
